#ifndef L1TriggerScouting_Phase3_plugins_alpaka_CombinatoricsModule_h
#define L1TriggerScouting_Phase3_plugins_alpaka_CombinatoricsModule_h

namespace ALPAKA_ACCELERATOR_NAMESPACE {

}  // namespace ALPAKA_ACCELERATOR_NAMESPACE

#endif  // L1TriggerScouting_Phase3_plugins_alpaka_CombinatoricsModule_h
